### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by andrea-ligios** [lets-blade/blade-demos#21]
Which is the right way to run the examples?
Apart from the Hello World one, the other seems to be not working out of the box.

Are they only code, which need to be copied and pasted elsewhere? 
Or are they supposed to be runnable from where they are?

**Comment by andrea-ligios** [comment]
I made it work through Visual Studio Code, but seems a very messy way. Any other?

**Comment by biezhi** [comment]
If you want to work under vscode, you need to install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) .
![image](https://user-images.githubusercontent.com/3849072/49724909-75259200-fca5-11e8-8afb-06a950e768c6.png)

It is possible to use "run" or "debug".

![image](https://user-images.githubusercontent.com/3849072/49724965-97b7ab00-fca5-11e8-8932-c6969984cf73.png)

**Comment by andrea-ligios** [comment]
Yes, thank you. I discovered it back then. 
I'm writing an article about Blade, it'll definitely help people overcome this JAR-building / IDE-running doubts. Stay tuned 👍
